Add HI crypto icon
unstoppabledomains/UI-Kit pull request #28
Opened 2023-03-06 10:59 UTC by domhhv

This PR adds a crypto icon for [$HI](https://hi.com/) currency support.

[Related issue](https://linear.app/unstoppable-domains/issue/ECH-717/new-currency-support-dollarhi)

![Screenshot 2023-03-10 at 14 53 09](https://user-images.githubusercontent.com/10829201/224320987-05dd8cbe-8358-4702-adaa-8855e83afb86.png)

2023-03-06 15:48 UTC, udhriaznov approved these changes
LGTM

2023-03-06 20:55 UTC, iurevych requested changes

2023-03-06 20:55 UTC, iurevych commented on src/icons/crypto/HI.tsx
> +        <filter id="drop-shadow-1" filterUnits="userSpaceOnUse">
Please consider the following:
1. Avoid raster graphics, it is better to take the SVG from their official website, and add some circle and change colors in Figma, to compose a simple icon which fits our standards (you can also ask Daniil)
2. Optimize the SVG code https://unstoppabledomains.slack.com/archives/C03702HJCN7/p1673957738038389

2023-03-10 20:46 UTC, iurevych approved these changes
👍

2023-03-10 20:47 UTC, iurevych commented on src/icons/crypto/HI.tsx
> +        <filter id="drop-shadow-1" filterUnits="userSpaceOnUse">
That can work

2023-03-13 10:09 UTC, merged